pipeline {
  agent {
    node{
      label 'slave'
    }
  }
   stages {
     stage('creating docker network') {
       steps {
         sh 'docker network create lms'
       }
     }
     stage('creating postgresql-db') {
       steps {
         sh 'docker container run -dt --name lms-db --network lms -p 5432:5432 -e POSTGRES_PASSWORD=password' postgres
       }
     }
   }
}
